language: python
python:
 - "3.6"
install:
 - pip install flake8
 - pip install codecov
 - pip install pytest-cov
 - pip install -r ./requirements.txt
 - pip install -e .
script:
 - flake8 --show-source dream
 - py.test --cov=./dream/
after_success:
 - codecov
