language: python
python:
 - "3.6"
install:
 - pip install codecov
 - pip install pytest-cov
 - pip install -e .
 - pip install -e .[test]
script:
 - flake8 --show-source dream
 - py.test --cov=./dream/
after_success:
 - codecov
