language: python
python:
 - "3.6"
services:
 - mysql
before_install:
 - mysql -e 'CREATE DATABASE IF NOT EXISTS dream_test;'
 - mysql dream_test < ./tests/server/init_test_db.sql
install:
 - pip install codecov
 - pip install pytest-cov
 - pip install -e .
 - pip install -e .[test]
script:
 - py.test --cov=./dream/
after_success:
 - codecov
